services:
  backend:
    build: ./GameFest-BackEnd
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=gamefest
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db

  frontend:
    build: ./GameFest-FrontEnd
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gamefest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./GameFest-BackEnd/gamefest.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
